name: youinroll_tools_stream
description: Controlling the camera on Android and iOS plus rtmp live streaming support. Based off the Camera plugin Social Network Community Youinroll Flutter.
version: 1.0.0
homepage: https://github.com/Xatiko540/flutter_youinroll_tools_stream/tree/main

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.5"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  path_provider: ^2.0.5
  video_player: ^2.2.5
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  pedantic: ^1.8.0+1

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.app.youinroll_tools_stream
        pluginClass: RtmppublisherPlugin
      ios:
        pluginClass: RtmppublisherPlugin
